#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") CONFIG_FILE

'$(basename "$0")' creates a QEMU virtual machine and installs Void Linux on it.
Must be run as root.
CONFIG_FILE must exist as a shell script with some necessary variable definitions in it.
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#
requireRoot

require qemu-img
require modprobe
require rmmod
require qemu-nbd
require sfdisk
require xbps-install
require xgenfstab
require xchroot

config_file="$1"

# Source config file
try test -f "$config_file"
try source "$config_file"

# Check if required variables are non-empty
try test -n "$vm_name"
try test -n "$img_size"

# Set other variables to default values, if empty
: ${timezone:=UTC}
: ${username:=me}
: ${userpwd:=$username}

# Keep basename
vm_name="$(basename "$vm_name")"

# Create image file if it doesn't exist
image_file="$vm_name.qcow2"
image_existed=false
if [ -f "$image_file" ]; then
    image_existed=true
else
    try qemu-img create -f qcow2 "$image_file" "$img_size"
fi

# Enable nbd
try modprobe nbd max_part=8
defer rmmod nbd
defer sleep 1
device="/dev/nbd0"
try test -e "$device"

# Connect image as network block device
try qemu-nbd --connect="$device" "$image_file"
defer qemu-nbd --disconnect "$device"
sleep 1

# Partition
if [ "$image_existed" = false ]; then
try sfdisk --label gpt --wipe always --wipe-partitions always "$device" << EOF
size=100M,type=21686148-6449-6E6F-744E-656564454649
type=L
EOF

# Format EFI partition
sleep 1
try test -e "${device}p1"
try mkfs.fat -F32 "${device}p1"

# Format root partition
try test -e "${device}p2"
try mkfs.ext4 "${device}p2"
fi # image_existed

# Mount root partition
rootdir="/mnt/$vm_name"
try mkdir -p "$rootdir"
try mount "${device}p2" "$rootdir"
defer umount "$rootdir"

# Mount EFI partition
try mkdir -p "$rootdir/boot/efi"
try mount "${device}p1" "$rootdir/boot/efi"
defer umount "$rootdir/boot/efi"

# Install base system & packages
if [ "$image_existed" = false ]; then
    arch="x86_64"
    try mkdir -p "$rootdir/var/db/xbps/keys"
    try cp /var/db/xbps/keys/* "$rootdir/var/db/xbps/keys/"
    REPO="https://repo-default.voidlinux.org/current"
#   REPO="https://repo-fastly.voidlinux.org/current"
    XBPS_ARCH="$arch" xbps-install -S -y -r "$rootdir" -R "$REPO" $(cat <<EOF
base-system
grub-x86_64-efi
EOF
)
#     XBPS_ARCH="$arch" xbps-install -S -y -r "$rootdir" -R "$REPO" $(cat <<EOF
# base-system
# grub-x86_64-efi
# chrony xtools time tmux curl wget zip unzip moreutils dos2unix
# git lazygit vim ffmpeg fd ripgrep fzf neovim htop dialog
# base-devel clang automake autoconf python3 python3-pip go nodejs shellcheck
# lighttpd asciidoc ruby-asciidoctor hugo
# xorg xinit xclip unclutter numlockx font-inconsolata-otf font-firacode vim-x11
# libXinerama-devel libXft-devel freetype-devel fontconfig-devel harfbuzz-devel
# EOF
# )

# Generate fstab
try mkdir -p "$rootdir/etc"
try xgenfstab -U "$rootdir" > "$rootdir/etc/fstab"

# Set locale
cat << EOF > "$rootdir/etc/default/libc-locales"
en_US.UTF-8 UTF-8 
EOF

# Set keyboard layout
if [ -n "$keymap" ]; then
cat << EOF > "$rootdir/etc/rc.conf"
KEYMAP="$keymap"
EOF
fi

# Set timezone
ln -sf "$rootdir/usr/share/zoneinfo/$timezone" "$rootdir/etc/localtime"

# Initial syncing of system clock to hardware clock
cat << EOF > "$rootdir/etc/adjtime"
0.0 0 0
0
UTC
EOF

# Grant sudo rights
cat << EOF > "$rootdir/etc/sudoers"
root ALL=(ALL) ALL
%wheel ALL=(ALL) ALL
%wheel ALL=NOPASSWD: /usr/bin/reboot, /usr/bin/shutdown
EOF

# Customize Grub config
cat << EOF > "$rootdir/etc/default/grub"
GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR="Void"
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 quiet video=1920x1080"
EOF

# Enable services
ln -s "$rootdir/etc/sv/dhcpcd" "$rootdir/etc/runit/runsvdir/default/"
ln -s "$rootdir/etc/sv/sshd" "$rootdir/etc/runit/runsvdir/default/"
ln -s "$rootdir/etc/sv/chronyd" "$rootdir/etc/runit/runsvdir/default/"

# chroot into root directory
xchroot "$rootdir" /bin/bash << EOF

# Generate chosen locale
xbps-reconfigure -f glibc-locales

# Create user
useradd -m "$username"
usermod -aG wheel "$username"
echo "$userpwd" | passwd "$username"

# Set up Grub
echo device="$device"
grub-install --target=x86_64-efi --efi-directory=/boot/efi --removable "$device"
grub-mkconfig -o /boot/grub/grub.cfg

# Finalize
# TODO: is -f needed?
#xbps-reconfigure -fa
xbps-reconfigure -a
EOF
fi # image_existed

# xchroot "$rootdir" /bin/bash

sleep 1
