#!/bin/bash

. rabot-utils
if [ "$?" -ne "0" ]; then
  echo "$0: Error while sourcing rabot-utils" >&2
  exit 1
fi

function showHelp
{
cat << DOCSTRING
Usage: $(basename "$0") CONFIG_FILE

'$(basename "$0")' creates a QEMU virtual machine and installs Void Linux on it.
Must be run as root.
CONFIG_FILE must exist as a shell script with some necessary variable definitions in it.
DOCSTRING
}

checkForHelp $1
minNumArgs 1 $#
requireRoot

require qemu-img
require modprobe
require rmmod
require qemu-nbd
require sfdisk
require xbps-install
require xgenfstab
require xchroot

config_file="$1"

# Source config file
try test -f "$config_file"
try source "$config_file"

# Check if required variables are non-empty
try test -n "$vm_name"
try test -n "$img_size"

# Set other variables to default values, if empty
: ${timezone:=UTC}
: ${username:=me}
: ${userpwd:=$username}

if [ ! "$reuse_image" = "true" ]; then
    # Directory $vm_name must not exist
    ###########################
    # TODO : REMOVE !!!!
    try rm -rf "$vm_name"
    ###########################
    try test ! -d "$vm_name"

# Create directory $vm_name and cd into it
try mkdir -p "$vm_name"
try cd "$vm_name"
fi # reuse_image

# Keep basename
vm_name="$(basename "$vm_name")"

# Create image file
image_file="$vm_name.qcow2"
if [ ! "$reuse_image" = "true" ]; then
    try qemu-img create -f qcow2 "$image_file" "$img_size"
fi # reuse_image

# Enable nbd
try modprobe nbd max_part=8
defer rmmod nbd
defer sleep 1
device="/dev/nbd0"
try test -e "$device"

# Connect image as network block device
try qemu-nbd --connect="$device" "$image_file"
defer qemu-nbd --disconnect "$device"
sleep 1

# Partition
if [ ! "$reuse_image" = "true" ]; then
try sfdisk --label gpt --wipe always --wipe-partitions always "$device" << EOF
size=100M,type=21686148-6449-6E6F-744E-656564454649
type=L
EOF

# Format EFI partition
sleep 1
try test -e "${device}p1"
try mkfs.fat -F32 "${device}p1"

# Format root partition
try test -e "${device}p2"
try mkfs.ext4 "${device}p2"
fi # reuse_image

# Mount root partition
rootdir="/mnt/$vm_name"
try mkdir -p "$rootdir"
try mount "${device}p2" "$rootdir"
defer umount "$rootdir"

# Mount EFI partition
try mkdir -p "$rootdir/boot/efi"
try mount "${device}p1" "$rootdir/boot/efi"
defer umount "$rootdir/boot/efi"

# Install base system & packages
if [ ! "$reuse_image" = "true" ]; then
    arch="x86_64"
    try mkdir -p "$rootdir/var/db/xbps/keys"
    try cp /var/db/xbps/keys/* "$rootdir/var/db/xbps/keys/"
    REPO="https://repo-default.voidlinux.org/current"
#   REPO="https://repo-fastly.voidlinux.org/current"
    XBPS_ARCH="$arch" xbps-install -S -y -r "$rootdir" -R "$REPO" $(cat <<EOF
base-system
grub-x86_64-efi
chrony xtools time tmux curl wget zip unzip moreutils dos2unix
git lazygit vim ffmpeg fd ripgrep fzf neovim htop dialog
base-devel clang automake autoconf python3 python3-pip go nodejs shellcheck
lighttpd asciidoc ruby-asciidoctor hugo
xorg xinit xclip unclutter numlockx font-inconsolata-otf font-firacode vim-x11
libXinerama-devel libXft-devel freetype-devel fontconfig-devel harfbuzz-devel
EOF
)

# Generate fstab
try mkdir -p "$rootdir/etc"
try xgenfstab -U "$rootdir" > "$rootdir/etc/fstab"

# Set keyboard layout
if [ -n "$keymap" ]; then
    echo "KEYMAP=\"$keymap\"" > "$rootdir/etc/rc.conf"
fi

# Grant sudo rights
cat << SUDOERSFILE > "$rootdir/etc/sudoers"
root ALL=(ALL) ALL
%wheel ALL=(ALL) ALL
%wheel ALL=NOPASSWD: /usr/bin/reboot, /usr/bin/shutdown
SUDOERSFILE

# Customize Grub config
cat << GRUBFILE > "$rootdir/etc/default/grub"
GRUB_DEFAULT=0
GRUB_TIMEOUT=0
GRUB_DISTRIBUTOR="Void"
GRUB_CMDLINE_LINUX_DEFAULT="loglevel=4 quiet video=1920x1080"
GRUBFILE

# TODO xchroot here and see if reconf locales is needed for timezone
#xchroot "$rootdir" /bin/bash

# TODO move creation of symlinks here

# chroot into root directory
xchroot "$rootdir" /bin/bash << EOF

# Generate locale files
xbps-reconfigure -f glibc-locales

# Set timezone
ln -sf "/usr/share/zoneinfo/$timezone" /etc/localtime

# Enable services
ln -s /etc/sv/dhcpcd /etc/runit/runsvdir/default/
ln -s /etc/sv/sshd /etc/runit/runsvdir/default/
ln -s /etc/sv/chronyd /etc/runit/runsvdir/default/

# Create user
useradd -m "$username"
usermod -aG wheel "$username"
echo "$userpwd" | passwd "$username"

# Set up Grub
grub-install --target=x86_64-efi --efi-directory=/boot/efi "$device"
grub-mkconfig -o /boot/grub/grub.cfg

# Finalize
xbps-reconfigure -fa
EOF
fi # reuse_image

xchroot "$rootdir" /bin/bash

sleep 1
