#!/usr/bin/env sh

########################################

# Config:

keymap="be-latin1"
target_device="/dev/sda"
username=bert
printf "Password for user $username: " && read password
hostname=hai
timezone=UTC
language_territory=en_US
charset=UTF-8
ssh_pubkey_file=

########################################

if [ -n "$ssh_pubkey_file" ]; then
    if [ ! -f "$ssh_pubkey_file" ]; then
        echo "ERROR: file doesn't exist: $ssh_pubkey_file"
        return
    fi
fi

# Set KB layout
[ -n "$keymap" ] && loadkeys "$keymap"

# Exit if no internet connection
ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1 || return

# Synchronize the system clock with NTP
timedatectl set-ntp true

# Partition target device
sfdisk --label gpt --wipe always --wipe-partitions always "$target_device" << EOF
size=32M,type=21686148-6449-6E6F-744E-656564454649
type=L
EOF

# Format partitions
# mkfs.fat -F 16 "${target_device}1"
mkfs.ext4 "${target_device}2"

# Mount the root partition :
mount "${target_device}2" /mnt

# Install the 'base' package group :
pacstrap /mnt base sudo

# Create an fstab file :
genfstab -U /mnt >> /mnt/etc/fstab

# Copy ssh pubkey file
if [ -n "$ssh_pubkey_file" ]; then
    cp "$ssh_pubkey_file" /mnt/root/ssh_pubkey
fi

# ‘chroot’ into the target filesystem
cat << EOF | arch-chroot /mnt

# Set timezone
ln -sf "/usr/share/zoneinfo/${timezone}" /etc/localtime

# Use UTC on the hardware clock
hwclock --systohc --utc

# Set the locale
echo "${language_territory}.${charset} ${charset}" > /etc/locale.gen
locale-gen
echo LANG=${language_territory}.${charset} > /etc/locale.conf

# Set the keyboard layout
echo KEYMAP="$keymap" > /etc/vconsole.conf

# Set the hostname
echo "$hostname" > /etc/hostname

# Set hostname as an alias for localhost
echo "127.0.0.1 $hostname.localdomain $hostname" >> /etc/hosts

# Add a non-root user, with ‘sudo’ rights
groupadd sudoers
useradd -G sudoers -m "$username" -p "$(openssl passwd -1 "$password")"
echo "%sudoers ALL=(ALL) ALL" >> /etc/sudoers

# Install some necessary packages:
pacman -Syu --noconfirm grub ufw git vim tmux time zip unzip dialog dos2unix hwinfo openssh knockd

# Enable ssh login with pubkey
cat << SSHDCFG > /etc/ssh/sshd_config
LogLevel VERBOSE
PermitRootLogin no
PubkeyAuthentication yes
PasswordAuthentication no
AuthorizedKeysFile .ssh/authorized_keys
ChallengeResponseAuthentication no
UsePAM yes
AllowUsers $username
SSHDCFG

# Put user's pubkey in the right place
if [ -n "$ssh_pubkey_file" ]; then
    su $username -c "mkdir -p /home/$username/.ssh"
    chmod 700 "/home/$username/.ssh"
    mv /root/ssh_pubkey /home/$username/.ssh/authorized_keys
    chown $username:$username /home/$username/.ssh/authorized_keys
    chmod 600 /home/$username/.ssh/authorized_keys
fi

# Add 5s delay to failed login attempts
cat << SYSLOGIN >> /etc/pam.d/system-login

auth optional pam_faildelay.so delay=5000000
SYSLOGIN

# Update & sort mirrorlist
# Disabled: takes too long
# reflector --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist

# Install grub
grub-install --target=i386-pc /dev/sda
# sed -i "s/^GRUB_TIMEOUT=.*$/GRUB_TIMEOUT=0/" /etc/default/grub
grub-mkconfig -o /boot/grub/grub.cfg
EOF
