#!/usr/bin/env sh

########################################

# Config:

keymap="be-latin1"
target_device="/dev/sda"
username=bert
printf "Password for user $username: " && read password
hostname=hai
timezone=UTC
language_territory=en_US
charset=UTF-8

########################################

# Set KB layout
[ -n "$keymap" ] && loadkeys "$keymap"

# Exit if no internet connection
ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1 || return

# Synchronize the system clock with NTP
timedatectl set-ntp true

# Partition target device
sfdisk --label gpt --wipe always --wipe-partitions always "$target_device" << EOF
size=2M,type=21686148-6449-6E6F-744E-656564454649
type=L
EOF

# Format partitions
# mkfs.fat -F 16 "${target_device}1"
mkfs.ext4 "${target_device}2"

# Mount the root partition :
mount "${target_device}2" /mnt

# Install the 'base' package group :
pacstrap /mnt base sudo reflector

# Create an fstab file :
genfstab -U /mnt >> /mnt/etc/fstab

# ‘chroot’ into the target filesystem
cat << EOF | arch-chroot /mnt

# Set timezone
ln -sf "/usr/share/zoneinfo/${timezone}" /etc/localtime

# Use UTC on the hardware clock
hwclock --systohc --utc

# Set the locale
echo "${language_territory}.${charset} ${charset}" > /etc/locale.gen
locale-gen
echo LANG=${language_territory}.${charset} > /etc/locale.conf

# Set the keyboard layout
echo KEYMAP="$keymap" > /etc/vconsole.conf

# Set the hostname
echo "$hostname" > /etc/hostname

# Set hostname as an alias for localhost
echo "127.0.0.1 $hostname.localdomain $hostname" >> /etc/hosts

# Add a non-root user, with ‘sudo’ rights
groupadd sudoers
useradd -G sudoers -m "$username" -p "$(openssl passwd -1 "$password")"
echo "%sudoers ALL=(ALL) ALL" >> /etc/sudoers

# Update & sort mirrorlist
# Disabled: takes too long
# reflector --age 12 --protocol https --sort rate --save /etc/pacman.d/mirrorlist

# Install some necessary packages:
pacman -Syu grub ufw git vim tmux time zip unzip dialog dos2unix hwinfo openssh knockd

EOF
