#!/usr/bin/env sh


########################################
# Config:

keyboard_layout="be-latin1"
target_device="/dev/sda"

########################################

# Prerequisites
which loadkeys > /dev/null 2>&1 || echo "Error: command 'loadkeys' not found" >&2 && return
which sfdisk > /dev/null 2>&1 || echo "Error: command 'sfdisk' not found" >&2 && return

# Set KB layout
[ -n "keyboard_layout" ] && loadkeys "$keyboard_layout"

# Exit if no internet connection
ping -c 1 -W 1 8.8.8.8 > /dev/null 2>&1 || return

# Synchronize the system clock with NTP
timedatectl set-ntp true

echo TEST

# Partition target device
# sfdisk --label gpt --wipe always --wipe-partitions always "$target_device" << EOF
# size=32M,type=U
# type=83
# EOF
#
#
#
